# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3143f532c7be9937fe66f0ae4262c207b885c6ed18fc2662da281f9a1b7c1d0aa13a2293c498ac27c4454003596b9e19681b84b4297babf9359b574417dca246

test:
  secret_key_base: c6bd4366ee6d7be3da150ad63bc24fb3f8c0ad495038f78f23b4ff731951d77f327c0a091fa006702806b96e249b4b5031d261e88edf5204ef8fb443839e4802

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
